services:

  flask-app:
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - postgresql
      - mediamtx
    networks:
      - omni_net
    volumes:
      - ./videos:/app/videos

  postgresql:
    image: postgres:15-alpine
    container_name: postgresql
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - omni_net

  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx
    ports:
      - "8554:8554"
    volumes:
      - ./videos:/videos
    networks:
      - omni_net

networks:
  omni_net:
    driver: bridge

volumes:
  postgres_data: