mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx
    ports:
      - "8554:8554"
      - "8555:8555"
      - "8556:8556"
      - "8557:8557"
      - "8888:8888"
    volumes:
      - ./mediamtx.yml:/mediamtx.yml
    networks:
      - omni_net